project_id = "nmmfquboslxhidghudrm"

[functions.send-password-reset]
verify_jwt = false

[functions.extract-document-metadata]
verify_jwt = true

[functions.send-changelog-email]
verify_jwt = false

[functions.create-partner]
verify_jwt = true

[functions.send-partner-otp]
verify_jwt = false

[functions.delete-user]
verify_jwt = true